services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:full
    ports:
      - "4000:4000"
      - "5173:5173"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      VITE_HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  app_node_modules:
